name: CI for Flask Web App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Flask app in background
      run: |
        nohup python app.py &
        sleep 5

    - name: UI Test over HTTP
      run: |
        curl --fail http://localhost:5000 || exit 1

    - name: Run OWASP Dependency Check
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/src \
          owasp/dependency-check \
          --scan /src \
          --format "HTML" \
          --out /src/dependency-check-report
