name: CI for Flask Web App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      flask:
        image: python:3.10-slim
        ports:
          - 5000:5000
        options: >-
          --health-cmd="curl --fail http://localhost:5000 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        volumes:
          - .:/app
        env:
          FLASK_APP: app.py
        command: >
          sh -c "pip install -r /app/requirements.txt && python /app/app.py"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Dependency Check (OWASP)
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/src \
          owasp/dependency-check \
          --scan /src \
          --format "HTML" \
          --out /src/dependency-check-report

    - name: UI Test over HTTP (basic test)
      run: |
        sleep 10
        curl --fail http://localhost:5000 || exit 1
